#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

fonts_add_cmd() {
  declare desc="Adds font to app"
  declare cmd="fonts:add" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  declare FONT_FILE="$2"
  local FONTS_PATH="$DOKKU_ROOT/$APP/fonts"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  [[ ! -f "$FONT_FILE" ]] && dokku_log_fail "Font not found: $FONT_FILE"

  mkdir -p "$FONTS_PATH"
  cp "$FONT_FILE" "$FONTS_PATH/"
}

fonts_add_cmd "$@"
