#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/fonts/functions"

fonts_remove_cmd() {
  declare desc="Removes font from app"
  declare cmd="fonts:remove" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  declare FONT_FILE="$2"
  local FONTS_PATH="$DOKKU_ROOT/$APP/fonts"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  [[ ! -f "$FONTS_PATH/$FONT_FILE" ]] && dokku_log_fail "Font not found: $FONT_FILE"

  rm "$FONTS_PATH/$FONT_FILE"
}

fonts_remove_cmd "$@"
